[tool.bumpversion]
current_version = "0.1.0+260913"
parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)\+(?P<release>\d+)'
serialize = ["{major}.{minor}.{patch}+{release}"]
commit = false
tag = false

[tool.bumpversion.parts.release]
calver_format = "{0Y}{0M}{0D}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "README.rst"
parse = '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)-(?P<release>\d+)'
serialize = ["{major}.{minor}.{patch}-{release}"]
search = "takoperator:{current_version}"
replace = "takoperator:{new_version}"

[[tool.bumpversion.files]]
filename = "src/takoperator/__init__.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "tests/test_takoperator.py"
search = '__version__ == "{current_version}"'
replace = '__version__ == "{new_version}"'
