[tox]
envlist = py314,py313,py312

[testenv]
skip_install = true
allowlist_externals = uv
passenv =
    SSH_AUTH_SOCK
    SKIP
setenv =
    UV_PROJECT_ENVIRONMENT = {envdir}
commands =
    uv sync --locked --python {envpython}
    uv run --locked --no-sync prek run --all-files
    uv run --locked --no-sync pytest --junitxml=pytest-{envname}.xml tests/
