[tox]
envlist = py314

[testenv]
skip_install = true
allowlist_externals = uv
passenv =
    SSH_AUTH_SOCK
setenv =
    UV_PROJECT_ENVIRONMENT = {envdir}
    UV_PYTHON = {envpython}
commands =
    uv sync --locked --python {envpython}
    uv run --locked --no-sync prek run --all-files
    uv run --locked --no-sync pytest --junitxml=pytest-{envname}.xml tests/
