apiVersion: v1
kind: ServiceAccount
metadata:
  name: tak-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tak-operator-platform
rules:
  - apiGroups: [platform.opendefence.fi]
    resources: [users, groups, roles]
    verbs: [get, list, watch, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tak-operator-platform
subjects:
  - kind: ServiceAccount
    name: tak-operator
    namespace: tak-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tak-operator-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tak-operator
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get, list, watch]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [create]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    resourceNames: [takoperator]
    verbs: [get, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tak-operator
subjects:
  - kind: ServiceAccount
    name: tak-operator
    namespace: tak-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tak-operator
