name: Publish main

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-monitor:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
        with:
          python-version: "3.14"
          uv-version: "0.12.13"
      - uses: pvarki/config-ci-library/.github/actions/snyk-monitor@main
        with:
          snyk-org: deployapp-products
          snyk-token: ${{ secrets.SNYK_TOKEN }}

  publish:
    name: Publish Docker image
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/publish-image@main
        with:
          product: tak
          component: operator
          dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          acr-repo: ${{ vars.ACR_REPO }}
          acr-username: ${{ vars.ACR_USERNAME }}
          acr-token: ${{ secrets.ACR_TOKEN }}
